### ISSUE TITLE
Options window doesn't fully display all options

### ISSUE THREAD

**Issue by Tele-Pet** [jawensi/DEMto3D-QGIS-Plugin#10]
The options window doesn't fully display all options and appears to cut off some of the options, especially the **Exaggeration terrain** option.

Environment details:
- Macbook Pro: retina display, running OS X (Yosemite, 10.10.5)
- QGIS 2.12, Lyon

Thanks

<img width="475" alt="screen shot 2015-11-03 at 12 21 33 pm" src="https://cloud.githubusercontent.com/assets/6935316/10915636/a53be582-8225-11e5-818c-07afdc97c96a.png">

**Comment by danielkschneider** [comment]
Others may sill have this problem so try this workaround: On my Windows machine I had to lower display resolution from 3200 to 1920 and font size from 200% to 100%. Going down to 1920p is not required but makes the labels big enough to read. Using 100% font size however is required (QGIS 2.18.4 / Demto3D 2.3.3)

**Comment by danielkschneider** [comment]
Just to make sure that you are aware that the problem is still here with the latest stable versions of QGIS and DEMto3D (2.18.14 and 2.3.3) as of Nov 2017. There is a second workaround. Just type blindly.:
- Click into the Scale box, then hit TAB
- Enter the exageration value, e.g. 2.0 and hit TAB again
- Enter the lowest point, e.g. 0 and hit TAB again
A screenshot is here: https://edutechwiki.unige.ch/en/File:QGIS-DEMto3d-gran_canaria.png 

- greetings ! Daniel

**Comment by jawensi** [comment]
Versión 3.1.1 Windows display fixed
